name: Apply Prettier style

on:
  pull_request:
    paths:
      - "docs/**"
      - "exploration/**"
      - "spec/**"
  push:
    branches-ignore:
      - main
    paths:
      - "docs/**"
      - "exploration/**"
      - "spec/**"

permissions:
  contents: write
  pull-requests: write

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - run: npm install --no-save prettier@3
      - run: npx prettier --write docs/ exploration/ spec/
      - name: git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: git add .
      - name: git commit & push any changes
        run: |
          git diff-index --quiet HEAD || (git commit -m "style: Apply Prettier" && git push)
