name: Validate test data

on:
  push:
    branches:
      - main
  pull_request:
    branches: '**'

jobs:
  run_all:
    name: Validate tests using schema
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Validate tests using the latest schema version
        run: |
            ajv validate --spec=draft2020 \
            -s $(ls -1v schemas/*/*schema.json | tail -1) \
            -d 'tests/**/*.json'
        working-directory: ./test
